// src/components/CreateCagnotteForm.tsx
import { useCallback, useEffect, useMemo, useState } from 'react';
import type { ChangeEvent } from 'react';
import { useForm } from 'react-hook-form';
import { z } from 'zod';
import { zodResolver } from '@hookform/resolvers/zod';
import { Stepper } from './ui/Stepper';
import { Button } from './ui/Button';
import { Input } from './ui/Input';
import { useToast } from './ui/Toast';
import { useTranslation } from '../lib/useTranslation';
import { QRCodeCanvas } from 'qrcode.react';

const STORAGE_KEY = 'tonti-create-draft';

const schema = z.object({
  title: z.string().min(4),
  description: z.string().min(20),
  category: z.string().min(3),
  coverData: z.string().min(10),
  visibility: z.enum(['public', 'private', 'unlisted']),
  goal: z.number().min(1000),
  minContribution: z.number().min(10),
  quickOptions: z.array(z.number().min(10)).length(3),
  shareMessage: z.string().min(10),
  allowAnonymous: z.boolean().default(true),
});

type FormValues = z.infer<typeof schema> & {
  slug: string;
};

const stepFields: Array<Array<keyof FormValues>> = [
  ['title', 'description', 'category'],
  ['coverData'],
  ['visibility'],
  ['goal', 'minContribution', 'quickOptions'],
  ['shareMessage'],
];

const defaultValues: FormValues = {
  title: '',
  description: '',
  category: '',
  coverData: '',
  visibility: 'public',
  goal: 5000,
  minContribution: 50,
  quickOptions: [50, 100, 200],
  shareMessage: "Rejoins ma cagnotte sur Tonti !",
  allowAnonymous: true,
  slug: '',
};

function toSlug(value: string) {
  return value
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9\u0600-\u06FF\s-]/g, '')
    .replace(/\s+/g, '-');
}

export function CreateCagnotteForm() {
  const { t } = useTranslation();
  const { push } = useToast();
  const [activeStep, setActiveStep] = useState(0);

  const stored = useMemo(() => {
    if (typeof window === 'undefined') return null;
    const draft = window.localStorage.getItem(STORAGE_KEY);
    return draft ? (JSON.parse(draft) as FormValues) : null;
  }, []);

  const {
    register,
    handleSubmit,
    watch,
    trigger,
    setValue,
    formState: { errors, isSubmitting },
  } = useForm<FormValues>({
    resolver: zodResolver(schema),
    defaultValues: stored ?? defaultValues,
    mode: 'onBlur',
  });

  const values = watch();

  useEffect(() => {
    const subscription = watch((value) => {
      const data = { ...value, slug: value.slug ?? toSlug(value.title ?? '') } as FormValues;
      window.localStorage.setItem(STORAGE_KEY, JSON.stringify(data));
    });
    return () => subscription.unsubscribe();
  }, [watch]);

  useEffect(() => {
    const slug = toSlug(values.title);
    if (slug && slug !== values.slug) {
      setValue('slug', slug, { shouldDirty: true, shouldTouch: true });
    }
  }, [values.title, values.slug, setValue]);

  const goToStep = useCallback(
    async (index: number) => {
      if (index > activeStep) {
        const valid = await trigger(stepFields[activeStep]);
        if (!valid) {
          push({ title: t('form.validation.required'), variant: 'error' });
          return;
        }
      }
      setActiveStep(Math.max(0, Math.min(stepFields.length - 1, index)));
    },
    [activeStep, trigger, push],
  );

  useEffect(() => {
    const handler = async (event: KeyboardEvent) => {
      if (event.key === 'ArrowRight') {
        event.preventDefault();
        await goToStep(activeStep + 1);
      }
      if (event.key === 'ArrowLeft') {
        event.preventDefault();
        await goToStep(activeStep - 1);
      }
    };
    window.addEventListener('keydown', handler);
    return () => window.removeEventListener('keydown', handler);
  }, [activeStep, goToStep]);

  const onSubmit = useCallback(
    async (_data: FormValues) => {
      const valid = await trigger(stepFields[activeStep]);
      if (!valid) {
        push({ title: t('form.validation.error'), variant: 'error' });
        return;
      }
      window.localStorage.removeItem(STORAGE_KEY);
      push({ title: t('form.save.success'), variant: 'success' });
    },
    [activeStep, push, t, trigger],
  );

  const handleCoverUpload = async (event: ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (!file) return;

    const reader = new FileReader();
    reader.onload = () => {
      const img = new Image();
      img.onload = () => {
        const canvas = document.createElement('canvas');
        const aspectRatio = 16 / 9;
        const width = img.width;
        const height = img.height;
        const targetWidth = width;
        const targetHeight = width / aspectRatio;
        const sy = Math.max(0, (height - targetHeight) / 2);
        canvas.width = 1280;
        canvas.height = 720;
        const ctx = canvas.getContext('2d');
        if (ctx) {
          ctx.drawImage(img, 0, sy, targetWidth, targetHeight, 0, 0, canvas.width, canvas.height);
          const dataUrl = canvas.toDataURL('image/jpeg', 0.85);
          setValue('coverData', dataUrl, { shouldDirty: true });
        }
      };
      if (typeof reader.result === 'string') {
        img.src = reader.result;
      }
    };
    reader.readAsDataURL(file);
  };

  const shareLink = `https://tonti.app/cagnotte/${values.slug || 'nouvelle-cagnotte'}`;

  return (
    <form className="grid gap-6 lg:grid-cols-[280px,1fr]" onSubmit={handleSubmit(onSubmit)}>
      <div className="space-y-4">
        <Stepper
          steps={[
            { id: 1, title: `${t('create.step1.title')}` },
            { id: 2, title: `${t('create.step2.title')}` },
            { id: 3, title: `${t('create.step3.title')}` },
            { id: 4, title: `${t('create.step4.title')}` },
            { id: 5, title: `${t('create.step5.title')}` },
          ]}
          activeStep={activeStep}
          onStepChange={goToStep}
        />
        <p className="text-xs text-white/60">{t('create.autosave')}</p>
      </div>
      <div className="space-y-8">
        {activeStep === 0 ? (
          <section className="space-y-4">
            <Input
              label={t('create.title.label')}
              placeholder="Titre de la cagnotte"
              {...register('title')}
              error={errors.title?.message}
            />
            <label className="flex w-full flex-col space-y-1 text-sm">
              <span className="font-medium text-white/90">{t('create.description.label')}</span>
              <textarea
                className="min-h-[150px] w-full rounded-xl border border-white/20 bg-white/5 px-3 py-2 text-sm text-white placeholder:text-white/40 focus:border-primary focus:ring-primary"
                {...register('description')}
                placeholder="Expliquez votre projet en détail"
              />
              {errors.description ? (
                <span className="text-xs text-red-400">{errors.description.message}</span>
              ) : (
                <span className="text-xs text-white/60">{t('create.description.helper')}</span>
              )}
            </label>
            <Input
              label={t('create.category.label')}
              placeholder="Solidarité"
              {...register('category')}
              error={errors.category?.message}
            />
          </section>
        ) : null}

        {activeStep === 1 ? (
          <section className="space-y-4">
            <div>
              <label className="flex w-full flex-col space-y-2 text-sm">
                <span className="font-medium text-white/90">Illustration (16:9)</span>
                <input
                  type="file"
                  accept="image/*"
                  onChange={handleCoverUpload}
                  className="w-full rounded-lg border border-dashed border-white/20 bg-white/5 px-3 py-8 text-center text-white/70 file:hidden"
                />
                {errors.coverData ? (
                  <span className="text-xs text-red-400">{errors.coverData.message}</span>
                ) : (
                  <span className="text-xs text-white/60">
                    Importez une image haute résolution. Le recadrage automatique respecte le ratio 16:9.
                  </span>
                )}
              </label>
            </div>
            {values.coverData ? (
              <div className="overflow-hidden rounded-3xl border border-white/10">
                <img src={values.coverData} alt="Aperçu" className="aspect-video w-full object-cover" />
              </div>
            ) : null}
          </section>
        ) : null}

        {activeStep === 2 ? (
          <section className="space-y-4">
            <fieldset className="grid gap-3">
              <legend className="text-sm font-semibold text-white/80">{t('create.visibility.legend')}</legend>
              {[
                { value: 'public', label: t('create.visibility.public'), helper: t('create.visibility.public.helper') },
                { value: 'private', label: t('create.visibility.private'), helper: t('create.visibility.private.helper') },
                { value: 'unlisted', label: t('create.visibility.unlisted'), helper: t('create.visibility.unlisted.helper') },
              ].map((option) => (
                <label key={option.value} className="flex items-start space-x-3 rounded-2xl border border-white/10 bg-white/[0.03] p-4">
                  <input
                    type="radio"
                    value={option.value}
                    {...register('visibility')}
                    className="mt-1 h-4 w-4 rounded-full border-white/30 bg-transparent text-primary focus:ring-primary"
                  />
                  <span>
                    <span className="block text-sm font-semibold text-white">{option.label}</span>
                    <span className="text-xs text-white/60">{option.helper}</span>
                  </span>
                </label>
              ))}
            </fieldset>
          </section>
        ) : null}

        {activeStep === 3 ? (
          <section className="space-y-4">
            <div className="grid gap-4 md:grid-cols-2">
              <Input
                label={t('create.goal.label')}
                type="number"
                min={100}
                {...register('goal', { valueAsNumber: true })}
                error={errors.goal?.message}
              />
              <Input
                label={t('create.minContribution.label')}
                type="number"
                min={10}
                {...register('minContribution', { valueAsNumber: true })}
                error={errors.minContribution?.message}
              />
            </div>
            <div className="space-y-2">
              <span className="text-sm font-medium text-white/90">{t('create.quickOptions.label')}</span>
              <div className="grid gap-3 md:grid-cols-3">
                {values.quickOptions.map((amount, index) => (
                  <Input
                    key={index}
                    type="number"
                    label={`${t('create.quickOptions.label')} ${index + 1}`}
                    {...register(`quickOptions.${index}` as const, { valueAsNumber: true })}
                    error={errors.quickOptions?.[index]?.message}
                  />
                ))}
              </div>
            </div>
          </section>
        ) : null}

        {activeStep === 4 ? (
          <section className="space-y-6">
            <label className="flex w-full flex-col space-y-2 text-sm">
              <span className="font-medium text-white/90">{t('create.invitation.label')}</span>
              <textarea
                className="min-h-[120px] w-full rounded-xl border border-white/20 bg-white/5 px-3 py-2 text-sm text-white placeholder:text-white/40 focus:border-primary focus:ring-primary"
                {...register('shareMessage')}
              />
              {errors.shareMessage ? <span className="text-xs text-red-400">{errors.shareMessage.message}</span> : null}
            </label>
            <div className="space-y-4 rounded-3xl border border-white/10 bg-white/[0.02] p-6">
              <p className="text-sm text-white/70">{t('create.share.helper')}</p>
              <div className="flex flex-col gap-3 md:flex-row md:items-center">
                <code className="flex-1 break-all rounded-2xl bg-black/40 px-4 py-3 text-xs">{shareLink}</code>
                <div className="flex gap-2">
                  <Button
                    type="button"
                    onClick={() => {
                      navigator.clipboard.writeText(shareLink);
                      push({ title: t('share.copy'), variant: 'success' });
                    }}
                  >
                    {t('share.copy')}
                  </Button>
                  <Button
                    type="button"
                    variant="ghost"
                    onClick={() => {
                      const url = new URL('https://wa.me/');
                      url.searchParams.set('text', `${values.shareMessage}\n${shareLink}`);
                      window.open(url.toString(), '_blank');
                    }}
                  >
                    {t('share.whatsapp')}
                  </Button>
                  <Button
                    type="button"
                    variant="ghost"
                    onClick={() => {
                      window.location.href = `mailto:?subject=${encodeURIComponent(values.title)}&body=${encodeURIComponent(`${values.shareMessage}\n${shareLink}`)}`;
                    }}
                  >
                    {t('share.email')}
                  </Button>
                </div>
              </div>
              <div className="flex flex-col items-center space-y-3">
                <QRCodeCanvas value={shareLink} size={180} bgColor="transparent" fgColor="#FFB300" includeMargin />
                <span className="text-xs text-white/60">{t('create.share.qr')}</span>
              </div>
            </div>
          </section>
        ) : null}

        <div className="flex items-center justify-between">
          <Button type="button" variant="ghost" onClick={() => goToStep(activeStep - 1)} disabled={activeStep === 0}>
            {t('form.prev')}
          </Button>
          {activeStep === stepFields.length - 1 ? (
            <Button type="submit" disabled={isSubmitting}>
              {t('form.finish')}
            </Button>
          ) : (
            <Button type="button" onClick={() => goToStep(activeStep + 1)}>
              {t('form.next')}
            </Button>
          )}
        </div>
      </div>
    </form>
  );
}

// src/components/forms/CreateCagnotteForm.vue
<script setup lang="ts">
import { reactive, ref, computed, watch, onMounted } from 'vue';
import { useI18n } from 'vue-i18n';
import { z } from 'zod';
import { useDebounceFn } from '@vueuse/core';
import Stepper, { type StepItem } from '../ui/Stepper.vue';
import TextInput from '../ui/TextInput.vue';
import TextArea from '../ui/TextArea.vue';
import SelectInput from '../ui/SelectInput.vue';
import BaseButton from '../ui/BaseButton.vue';
import GlassCard from '../ui/GlassCard.vue';
import { generateSlug } from '../../utils/slug';
import { safeStorage } from '../../utils/storage';
import { useToast } from '../../composables/useToast';
import { copyToClipboard, emailShareUrl, whatsappShareUrl } from '../../utils/share';
import { formatCurrency } from '../../utils/currency';
import { i18n } from '../../i18n';
import VueCropper from 'vue-cropperjs';
import 'cropperjs/dist/cropper.css';
import QrcodeVue from 'qrcode.vue';

const { t } = useI18n();
const { push } = useToast();

const steps = computed<StepItem[]>(() => [
  { id: 'description', label: t('create.step.description') },
  { id: 'illustration', label: t('create.step.illustration') },
  { id: 'visibility', label: t('create.step.visibility') },
  { id: 'amounts', label: t('create.step.amounts') },
  { id: 'invitations', label: t('create.step.invitations') },
]);

const current = ref('description');

const categories = [
  { value: 'urgence', label: 'Urgence' },
  { value: 'education', label: 'Éducation' },
  { value: 'sante', label: 'Santé' },
  { value: 'entrepreneuriat', label: 'Entrepreneuriat' },
  { value: 'sport', label: 'Sport' },
];

interface FormState {
  title: string;
  description: string;
  category: string;
  visibility: 'public' | 'private' | 'unlisted';
  goal: number;
  minimum: number;
  quickOptions: number[];
  slug: string;
  coverRaw: string | null;
  coverCropped: string | null;
}

const form = reactive<FormState>({
  title: '',
  description: '',
  category: '',
  visibility: 'public',
  goal: 5000,
  minimum: 20,
  quickOptions: [50, 100, 200],
  slug: '',
  coverRaw: null,
  coverCropped: null,
});

const errors = reactive<Record<string, string>>({});
const lockKey = 'tonti_form_draft_v1';

const descriptionSchema = z.object({
  title: z.string().min(4),
  description: z.string().min(20),
  category: z.string().min(1),
});

const illustrationSchema = z.object({
  coverCropped: z.string().min(1),
});

const visibilitySchema = z.object({
  visibility: z.enum(['public', 'private', 'unlisted']),
});

const amountsSchema = z.object({
  goal: z.number().min(100),
  minimum: z.number().min(10),
  quickOptions: z.array(z.number().min(10)).min(1),
});

const validators: Record<string, z.ZodSchema> = {
  description: descriptionSchema,
  illustration: illustrationSchema,
  visibility: visibilitySchema,
  amounts: amountsSchema,
  invitations: z.object({}),
};

const cropper = ref<InstanceType<typeof VueCropper> | null>(null);
const isSaving = ref(false);
const hasRestored = ref(false);
let skipNextSave = true;

const stepOrder = computed(() => steps.value.map((step) => step.id));

const saveDraft = useDebounceFn(() => {
  if (typeof window === 'undefined' || !hasRestored.value) return;
  safeStorage.set(lockKey, JSON.stringify(form));
  push({ level: 'success', title: t('create.actions.saved'), duration: 2500 });
}, 800);

watch(
  () => ({ ...form }),
  () => {
    if (skipNextSave) {
      skipNextSave = false;
      return;
    }
    isSaving.value = true;
    saveDraft();
    if (typeof window !== 'undefined') {
      window.setTimeout(() => {
        isSaving.value = false;
      }, 900);
    } else {
      isSaving.value = false;
    }
  },
  { deep: true }
);

watch(
  () => form.title,
  (title) => {
    form.slug = generateSlug(title);
  }
);

onMounted(() => {
  const stored = safeStorage.get(lockKey);
  if (stored) {
    try {
      const payload = JSON.parse(stored) as FormState;
      Object.assign(form, payload);
    } catch (error) {
      console.error('Unable to restore draft', error);
    }
  }
  hasRestored.value = true;
});

const validateCurrent = () => {
  const schema = validators[current.value];
  const result = schema.safeParse(form);
  Object.keys(errors).forEach((key) => delete errors[key]);
  if (!result.success) {
    result.error.issues.forEach((issue) => {
      const field = issue.path[0];
      errors[field as string] = issue.message;
    });
    return false;
  }
  return true;
};

const goTo = (id: string) => {
  const targetIndex = stepOrder.value.indexOf(id);
  const currentIndex = stepOrder.value.indexOf(current.value);
  if (targetIndex <= currentIndex) {
    current.value = id;
    return;
  }
  if (validateCurrent()) {
    current.value = id;
  }
};

const next = () => {
  if (!validateCurrent()) return;
  const index = stepOrder.value.indexOf(current.value);
  if (index < stepOrder.value.length - 1) {
    current.value = stepOrder.value[index + 1];
  }
};

const previous = () => {
  const index = stepOrder.value.indexOf(current.value);
  if (index > 0) {
    current.value = stepOrder.value[index - 1];
  }
};

const handleKeydown = (event: KeyboardEvent) => {
  if (event.key === 'ArrowRight') {
    event.preventDefault();
    next();
  }
  if (event.key === 'ArrowLeft') {
    event.preventDefault();
    previous();
  }
  if (event.key === 'Enter' && event.metaKey) {
    event.preventDefault();
    submit();
  }
};

const uploadCover = async (event: Event) => {
  const file = (event.target as HTMLInputElement).files?.[0];
  if (!file) return;
  const reader = new FileReader();
  reader.onload = () => {
    form.coverRaw = reader.result as string;
  };
  reader.readAsDataURL(file);
};

const confirmCrop = () => {
  if (!cropper.value) return;
  const canvas = cropper.value.getCroppedCanvas({ aspectRatio: 16 / 9, width: 1200 });
  form.coverCropped = canvas.toDataURL('image/jpeg');
  push({ level: 'success', title: 'Image recadrée en 16:9' });
};

const addQuickOption = () => {
  const nextValue = Math.max(...form.quickOptions, form.minimum) + 50;
  form.quickOptions = [...form.quickOptions, nextValue];
};

const removeQuickOption = (amount: number) => {
  form.quickOptions = form.quickOptions.filter((value) => value !== amount);
};

const shareUrl = computed(() => `https://tonti.app/cagnotte/${form.slug || 'ma-nouvelle-cagnotte'}`);

const copyLink = async () => {
  await copyToClipboard(shareUrl.value);
  push({ level: 'success', title: t('create.invitations.copied') });
};

const shareWhatsapp = () => {
  if (typeof window !== 'undefined') {
    window.open(whatsappShareUrl(shareUrl.value), '_blank');
  }
};

const shareEmail = () => {
  if (typeof window !== 'undefined') {
    window.open(emailShareUrl('Cagnotte Tonti', shareUrl.value), '_blank');
  }
};

const submit = () => {
  if (!validateCurrent()) {
    push({ level: 'error', title: 'Veuillez corriger les erreurs' });
    return;
  }
  push({ level: 'success', title: 'Cagnotte prête à être publiée', description: 'Connectez votre futur backend de paiement.' });
  safeStorage.remove(lockKey);
};
</script>

<template>
  <div
    class="space-y-10"
    @keydown="handleKeydown"
    tabindex="0"
    role="form"
    aria-labelledby="create-title"
  >
    <Stepper :steps="steps" :current="current" @select="goTo" />

    <GlassCard class="space-y-6">
      <section v-if="current === 'description'" class="space-y-6">
        <header class="space-y-2">
          <h2 class="text-xl font-semibold">{{ t('create.step.description') }}</h2>
          <p class="text-sm text-white/60">{{ t('create.intro') }}</p>
        </header>
        <div class="grid gap-6">
          <TextInput
            id="title"
            v-model="form.title"
            :label="t('create.description.titleLabel')"
            :placeholder="t('create.description.titlePlaceholder')"
            :error="errors.title"
            required
          />
          <TextArea
            id="description"
            v-model="form.description"
            :label="t('create.description.descriptionLabel')"
            :placeholder="t('create.description.descriptionPlaceholder')"
            :error="errors.description"
            rows="6"
          />
          <SelectInput
            id="category"
            v-model="form.category"
            :label="t('create.description.categoryLabel')"
            :options="categories"
            :error="errors.category"
          />
        </div>
      </section>

      <section v-else-if="current === 'illustration'" class="space-y-6">
        <header class="space-y-2">
          <h2 class="text-xl font-semibold">{{ t('create.step.illustration') }}</h2>
          <p class="text-sm text-white/60">{{ t('create.illustration.helper') }}</p>
        </header>
        <div class="space-y-4">
          <input type="file" accept="image/*" @change="uploadCover" />
          <div v-if="form.coverRaw" class="space-y-4">
            <VueCropper
              ref="cropper"
              :src="form.coverRaw"
              drag-mode="move"
              :aspect-ratio="16 / 9"
              class="h-64 w-full rounded-2xl bg-black"
            />
            <BaseButton type="button" @click="confirmCrop">{{ t('create.illustration.changeButton') }}</BaseButton>
          </div>
          <img v-if="form.coverCropped" :src="form.coverCropped" alt="Preview" class="h-48 w-full rounded-2xl object-cover" />
          <p v-if="errors.coverCropped" class="text-sm text-red-400">{{ errors.coverCropped }}</p>
        </div>
      </section>

      <section v-else-if="current === 'visibility'" class="space-y-6">
        <header class="space-y-2">
          <h2 class="text-xl font-semibold">{{ t('create.step.visibility') }}</h2>
          <p class="text-sm text-white/60">{{ t('create.visibility.helper') }}</p>
        </header>
        <div class="grid gap-4 sm:grid-cols-3">
          <label class="flex cursor-pointer flex-col gap-3 rounded-2xl border border-white/10 bg-white/5 p-4 hover:border-primary">
            <input v-model="form.visibility" type="radio" value="public" class="sr-only" />
            <span class="text-lg font-semibold">{{ t('create.visibility.public') }}</span>
            <p class="text-sm text-white/60">Affichée dans les recherches Tonti.</p>
          </label>
          <label class="flex cursor-pointer flex-col gap-3 rounded-2xl border border-white/10 bg-white/5 p-4 hover:border-primary">
            <input v-model="form.visibility" type="radio" value="private" class="sr-only" />
            <span class="text-lg font-semibold">{{ t('create.visibility.private') }}</span>
            <p class="text-sm text-white/60">Accès limité aux invités approuvés.</p>
          </label>
          <label class="flex cursor-pointer flex-col gap-3 rounded-2xl border border-white/10 bg-white/5 p-4 hover:border-primary">
            <input v-model="form.visibility" type="radio" value="unlisted" class="sr-only" />
            <span class="text-lg font-semibold">{{ t('create.visibility.unlisted') }}</span>
            <p class="text-sm text-white/60">Accessible uniquement via le lien direct.</p>
          </label>
        </div>
        <p v-if="errors.visibility" class="text-sm text-red-400">{{ errors.visibility }}</p>
      </section>

      <section v-else-if="current === 'amounts'" class="space-y-6">
        <header class="space-y-2">
          <h2 class="text-xl font-semibold">{{ t('create.step.amounts') }}</h2>
          <p class="text-sm text-white/60">Définissez des objectifs réalistes pour motiver vos contributeurs.</p>
        </header>
        <div class="grid gap-6 md:grid-cols-2">
          <TextInput
            id="goal"
            v-model="form.goal"
            type="number"
            :label="t('create.amounts.goalLabel')"
            :error="errors.goal"
          />
          <TextInput
            id="minimum"
            v-model="form.minimum"
            type="number"
            :label="t('create.amounts.minContributionLabel')"
            :error="errors.minimum"
          />
        </div>
        <div class="space-y-3">
          <p class="text-sm font-semibold">{{ t('create.amounts.quickOptionsLabel') }}</p>
          <div class="flex flex-wrap gap-2">
            <button
              v-for="amount in form.quickOptions"
              :key="amount"
              type="button"
              class="rounded-full border border-white/20 px-4 py-2 text-sm text-white/80 hover:border-primary"
              @click="removeQuickOption(amount)"
            >
              {{ formatCurrency(amount, i18n.global.locale.value === 'ar' ? 'ar-MA' : 'fr-MA') }}
              <span class="ml-1 text-xs text-white/50">×</span>
            </button>
            <BaseButton variant="ghost" type="button" @click="addQuickOption">{{ t('create.amounts.addOption') }}</BaseButton>
          </div>
        </div>
        <p v-if="errors.quickOptions" class="text-sm text-red-400">{{ errors.quickOptions }}</p>
      </section>

      <section v-else-if="current === 'invitations'" class="space-y-6">
        <header class="space-y-2">
          <h2 class="text-xl font-semibold">{{ t('create.step.invitations') }}</h2>
          <p class="text-sm text-white/60">{{ t('create.invitations.shareDescription') }}</p>
        </header>
        <div class="grid gap-6 lg:grid-cols-2">
          <div class="space-y-4">
            <p class="text-sm text-white/70">Lien</p>
            <div class="rounded-2xl border border-white/10 bg-white/5 p-4">
              <p class="text-sm break-all text-white/80">{{ shareUrl }}</p>
              <div class="mt-3 flex flex-wrap gap-3">
                <BaseButton type="button" size="sm" @click="copyLink">{{ t('create.invitations.copyLink') }}</BaseButton>
                <BaseButton type="button" size="sm" variant="ghost" @click="shareWhatsapp">
                  {{ t('create.invitations.whatsapp') }}
                </BaseButton>
                <BaseButton type="button" size="sm" variant="ghost" @click="shareEmail">
                  {{ t('create.invitations.email') }}
                </BaseButton>
              </div>
            </div>
            <p class="text-xs text-white/50">{{ t('create.actions.saving') }} {{ isSaving ? '…' : '' }}</p>
          </div>
          <div class="space-y-4">
            <p class="text-sm text-white/70">{{ t('create.invitations.qrLabel') }}</p>
            <div class="inline-flex rounded-2xl border border-white/10 bg-white p-4">
              <QrcodeVue :value="shareUrl" :size="160" level="H" render-as="svg" />
            </div>
          </div>
        </div>
      </section>
    </GlassCard>

    <div class="flex flex-wrap items-center justify-between gap-4">
      <BaseButton variant="ghost" type="button" @click="previous">{{ t('create.actions.previous') }}</BaseButton>
      <div class="flex items-center gap-3">
        <span v-if="isSaving" class="text-sm text-white/60">{{ t('create.actions.saving') }}</span>
        <BaseButton v-if="current !== 'invitations'" type="button" @click="next">{{ t('create.actions.next') }}</BaseButton>
        <BaseButton v-else type="button" @click="submit">{{ t('create.actions.submit') }}</BaseButton>
      </div>
    </div>
  </div>
</template>
